#pragma once

enum {
    RADIO_IFACE_CMD_GET_MODE,
    RADIO_IFACE_CMD_SET_MODE,
    RADIO_IFACE_CMD_GET_BANDWIDTH,
    RADIO_IFACE_CMD_SET_BANDWIDTH,
    RADIO_IFACE_CMD_GET_SQUELCH_ENABLED,
    RADIO_IFACE_CMD_SET_SQUELCH_ENABLED,
    RADIO_IFACE_CMD_GET_SQUELCH_LEVEL,
    RADIO_IFACE_CMD_SET_SQUELCH_LEVEL,
    RADIO_IFACE_CMD_GET_IFNR_ENABLED,
    RADIO_IFACE_CMD_SET_IFNR_ENABLED,
    RADIO_IFACE_CMD_GET_IFNR_BINS,
    RADIO_IFACE_CMD_SET_IFNR_BINS,
    RADIO_IFACE_CMD_GET_IFNR_STRENGTH,
    RADIO_IFACE_CMD_SET_IFNR_STRENGTH,
    RADIO_IFACE_CMD_GET_IFNR_PROFILE,
    RADIO_IFACE_CMD_SET_IFNR_PROFILE,
};

enum {
    RADIO_IFACE_MODE_NFM,
    RADIO_IFACE_MODE_WFM,
    RADIO_IFACE_MODE_AM,
    RADIO_IFACE_MODE_DSB,
    RADIO_IFACE_MODE_USB,
    RADIO_IFACE_MODE_CW,
    RADIO_IFACE_MODE_LSB,
    RADIO_IFACE_MODE_RAW,
    RADIO_IFACE_MODE_DRM,
    RADIO_IFACE_MODE_MORSE,
    RADIO_IFACE_MODE_DMR
};
